backend:
  name: git-gateway
#  name: test-repo
  branch: main # Branch to update (optional; defaults to master)
local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']
media_folder: public/media/
public_folder: /media
collections:
  - label: "Main Site Pages"
    name: "pages"
    files:
    - label: "Home Page"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Site Title", name: "title", widget: "string", required: true }
        - { label: "Site Banner Image", name: "banner", widget: "image", required: true }
        - { label: "About Mom and Kittens", name: "about", widget: "markdown" }
        - label: "Kitten Summaries"
          name: "cats"
          widget: list
          fields:
            - {
              label: "Kitten",
              name: "catSummary",
              widget: "relation",
              collection: "cats",
              value_field: "{ \"name\": \"`{{name}}`\",  \"slug\": \"{{slug}}\", \"gender\": \"{{gender}}\", \"adopted\": \"{{adopted}}\", \"picture\": \"{{picture}}\", \"about\": \"`{{about}}`\" }",
              display_fields: ["{{name}} - {{gender}}"],
              search_fields: ["name"]
            }
        - label: "Gallery Item"
          name: "gallery"
          widget: list
          fields:
            - {
              label: "Description",
              name: "description",
              required: false,
              widget: "string"
            }
            - {
              label: "Image or Youtube Link",
              name: "src",
              widget: "image"
            }
    - label: "Adoption Info"
      name: "adoption-info"
      file: "content/adoption-info.md"
      fields:
        - { label: "Page Content", name: "body", widget: "markdown" }
    - label: "Cat Ownership"
      name: "cat-ownership"
      file: "content/cat-ownership.md"
      fields:
        - { label: "Page Content", name: "body", widget: "markdown" }
  - label: "Cat Pages"
    name: "cats"
    folder: "content/cats"
    create: true
    identifier_field: name
    fields:
      - { label: "Cat Name", name: "name", widget: "string" }
      - label: "Gender"
        name: "gender"
        widget: "select"
        required: false
        options: [ "Male", "Female" ]
      - label: "Adopted"
        name: "adopted"
        widget: "select"
        required: false
        options: [ "Yes", "No" ]
      - { label: "Featured Picture", name: "picture", widget: "image" }
      - { label: "About This Cat", name: "about", widget: "markdown" }
      - label: "Gallery Item"
        name: "gallery"
        widget: list
        fields:
          - {
            label: "Description",
            name: "description",
            required: false,
            widget: "string"
          }
          - {
            label: "Image or Youtube Link",
            name: "src",
            widget: "image"
          }

